USE talent_pipeline_platform;

CREATE TABLE IF NOT EXISTS promotion_decision_records (
  decision_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  candidate_employee_id VARCHAR(20) NOT NULL,
  employee_name VARCHAR(50),
  department VARCHAR(50),
  current_position VARCHAR(100),
  current_job_level VARCHAR(20),
  current_rank_name VARCHAR(20),
  target_position VARCHAR(100) NOT NULL,
  target_department VARCHAR(50),
  match_score DECIMAL(5,2),
  recommendation VARCHAR(30),
  succession_level VARCHAR(20),
  performance_score DECIMAL(5,2),
  potential_score DECIMAL(5,2),
  attrition_risk_score INT,
  attrition_risk VARCHAR(20),
  decision_reason TEXT,
  risk_warning TEXT,
  development_plan TEXT,
  hr_comment TEXT,
  manager_comment TEXT,
  final_opinion TEXT,
  decision_status VARCHAR(30) NOT NULL DEFAULT 'agent_generated',
  created_by VARCHAR(50),
  reviewed_by VARCHAR(50),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_candidate_employee_id (candidate_employee_id),
  KEY idx_target_position (target_position),
  KEY idx_department (department),
  KEY idx_decision_status (decision_status),
  KEY idx_created_at (created_at)
);
